name: Deploy Back Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Symfony back to OVH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.OVH_SSH_PRIVATE_KEY }}

      - name: Add OVH host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.OVH_PORT }} ${{ secrets.OVH_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy script on OVH
        run: |
          ssh -p ${{ secrets.OVH_PORT }} ${{ secrets.OVH_USER }}@${{ secrets.OVH_HOST }} "sh ~/deploy-back-prod.sh"